version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  ApplicationStop:
    - location: scripts/codedeploy/application_stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/codedeploy/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/codedeploy/application_start.sh
      timeout: 300
      runas: root
